#spring.application.name=modeloUml1
#spring.application.name=projeto1
#spring.profiles.active=${APP_PROFILE:test}
#spring.jpa.open-in-view=false

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

# H2 Connection - Configurado para salvar em um arquivo na raiz do projeto
spring.datasource.url=jdbc:h2:file:./testdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=

# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Diz ao Hibernate para criar as tabelas se não existirem, ou atualizá-las.
# MUITO IMPORTANTE: Não use 'create-drop' com um banco em arquivo, ou seus dados serão apagados a cada reinicialização.
spring.jpa.hibernate.ddl-auto=update

# Show SQL and format it
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Diz ao Hibernate para criar/atualizar as tabelas
# spring.jpa.hibernate.ddl-auto=update
